version: '3'

services: 
  jenkins:
    image: localhost:5000/jenkins-com-docker:lts-jdk11
    restart: always
    ports:
      - "8008:8080"
      - "50000:50000"
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_CERT_PATH: 
      DOCKER_TLS_VERIFY: 
    volumes: 
      - /DATA/AppData/Jenkins/jenkins_home:/var/jenkins_home
      - /DATA/AppData/Jenkins/.m2:/var/jenkins_home/.m2
    container_name: jenkins
